<Project>
	<ItemGroup Condition="'$(TargetFramework)' != 'net472'">
		<Compile Remove="$(MSBuildProjectDirectory)/**/*.net4x.cs" />
		<None Include="$(MSBuildProjectDirectory)/**/*.net4x.cs" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net472'">
		<Compile Remove="$(MSBuildProjectDirectory)/**/*.net5plus.cs" />
		<None Include="$(MSBuildProjectDirectory)/**/*.net5plus.cs" />
	</ItemGroup>
</Project>
