name: Build and test
on:
  pull_request:
  push:
    branches: master
jobs:
  test:
    name: Build and test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-dotnet
      - name: Unit tests
        run: dotnet test -c Release --framework net50 test/D2L.Security.OAuth2.UnitTests/D2L.Security.OAuth2.UnitTests.csproj
      - name: Integration tests
        run: dotnet test -c Release --framework net50 test/D2L.Security.OAuth2.IntegrationTests/D2L.Security.OAuth2.IntegrationTests.csproj
