name: CI

on:
  pull_request:
  push:
    branches: master
    tags:
      - v*

env:
  VERSION_PREFIX: 12.4.0

jobs:

  linux:
    name: Build and test (Linux)
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-dotnet

      - name: Unit tests
        run: dotnet test -c Release --framework net60 test/D2L.Security.OAuth2.UnitTests/D2L.Security.OAuth2.UnitTests.csproj
      - name: Integration tests
        run: dotnet test -c Release --framework net60 test/D2L.Security.OAuth2.IntegrationTests/D2L.Security.OAuth2.IntegrationTests.csproj

  windows:
    name: Build and test (Windows)
    runs-on: windows-latest
    timeout-minutes: 10

    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-dotnet

      - run: dotnet tool restore
      - name: Generate version properties
        run: dotnet ci-version-properties --output VersionInfo.props && cat VersionInfo.props

      - name: Build
        run: dotnet build -c Release

      - name: Test
        run: dotnet test -c Release --no-build

      - name: Archive
        uses: Brightspace/third-party-actions@actions/upload-artifact
        with:
          name: D2L.Security.OAuth2.${{ github.sha }}
          path: src/**/*.symbols.nupkg
